version: "3.8"

services:
  server-web:
    image: nginx:alpine
    container_name: server-web
    ports:
      - "8080:80"
    volumes:
      - ./web:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /app
    mem_limit: 12288000
    cpus: 2
