apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  serviceName: service-mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: init-mongo
          image: mongo:3.4.1
          command:
            - bash
            - /config/init.sh
          volumeMounts:
            - mountPath: /config
              name: config
        - name: mongodb
          image: mongo:3.4.1
          command:
            - mongod
            - --replSet
            - rs0
          ports:
            - containerPort: 27017
              name: web
              protocol: TCP
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      volumes:
        - configMap:
            defaultMode: 420
            name: mongo-init
          name: config
