apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
      env: dev
  template:
    metadata:
      labels:
        app: frontend-app
        env: dev
    spec:
      containers:
        - name: frontend-container
          image: gcr.io/curso-docker10/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: SERVICE_BACKEND1
              value: "api/message"
          livenessProbe:
            httpGet:
              path: "/healthcheck"
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 3
          resources:
            limits:
              memory: "200Mi"
              cpu: "0.5"
            requests:
              memory: "64Mi"
              cpu: "0.1"
