apiVersion: v1
kind: ConfigMap
metadata:
  name: vars
  labels:
    app: frontend
data:
  db_host: dev.host.local
  db_user: dev_user
  script: |
    #!/bin/bash
    echo HOST = $DB_HOST y USER = $DB_USER > /usr/share/nginx/html/information.html;
    nginx -g;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: frontend
data:
  nginx: |
    server {
      listen 8080;
      server_name localhost;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }

      error_page 500 502 503 504 /50x.html;

      location = /50x.html {
        root /usr/share/nginx/html;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
          command: ["/opt/script.sh"]
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: vars
                  key: db_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: vars
                  key: db_user
          volumeMounts:
            - name: nginx-vol
              mountPath: /etc/nginx/conf.d
            - name: script-vol
              mountPath: /opt
      volumes:
        - name: nginx-vol
          configMap:
            name: nginx-config
            items:
              - key: nginx
                path: default.conf
        - name: script-vol
          configMap:
            name: vars
            defaultMode: 0777
            items:
              - key: script
                path: script.sh
