apiVersion: v1
kind: Secret
metadata:
  name: supersecreto
type: Opaque
data:
  username: bXVuZG9zb2xhcg==
  password: M2xRdWlqb3RlRDNMQW1hbmNoYQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: server-web
          image: nginx:alpine
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: supersecreto
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: supersecreto
                  key: password
          volumeMounts:
            - name: test
              mountPath: "/opt"
              readOnly: true
      volumes:
        - name: test
          secret:
            secretName: supersecreto
            items:
              - key: username
                path: user.txt
