apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-set
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: container01
          image: python:3.6-alpine
          command:
            [
              "sh",
              "-c",
              "echo 'contenedor1' > index.html && python -m http.server 8082",
            ]
